package database;
/**
  * Autogenerated by Lisptorq 0.1.4 
*/
import java.sql.*;

public class BaseHistoryUsersPeer  { 

	public static void doInsert(BaseHistoryUsers args0)
	throws Exception{
        Connection connection = Database.getConnection(); 
        doSave(args0,false,connection);
        Database.release(connection);
	} 

	public static void doInsert(BaseHistoryUsers args0,Connection connection)
	throws Exception{ 
        doSave(args0,false,connection);
	} 

	public static void doUpdate(BaseHistoryUsers args0)
	throws Exception{ 	
        Connection connection = Database.getConnection(); 
        doSave(args0,true,connection);
        Database.release(connection);
    }

	public static void doUpdate(BaseHistoryUsers args0,Connection connection)
	throws Exception{ 	
        doSave(args0,true,connection);
    }

	private static void doSave(BaseHistoryUsers args0, boolean isUpdate, Connection connection)
	throws Exception{ 

        Statement statement = connection.createStatement();        
        String query = "";
        if(isUpdate){
            query = "UPDATE HistoryUsers SET " + " count = " + Criteria.escape(args0.getCount()) + " WHERE " + " id = " + Criteria.escape(args0.getId()) + "";
            statement.executeUpdate(query);
        }else{
            query = "INSERT INTO HistoryUsers ( count ) VALUES ( " + Criteria.escape(args0.getCount()) + " )";         
            statement.execute(query,Statement.RETURN_GENERATED_KEYS);
            ResultSet rs = statement.getGeneratedKeys();
            if(rs.next()){
                args0.id=rs.getInt(1);
            }
        }   
        statement.close();  
        args0.saved = true;      
	}
 
	public static void doDelete(Criteria args0)
	throws Exception{ 
        Connection connection = Database.getConnection();
        doDelete(args0,connection);
        Database.release(connection);
    } 

	public static void doDelete(Criteria args0, Connection connection)
	throws Exception{ 
        Statement statement = connection.createStatement();
        statement.executeUpdate(args0.deleteSQL("HISTORYUSERS"));
        statement.close();
    } 

	public static void doDelete(BaseHistoryUsers args0)
	throws Exception{ 
        Connection connection = Database.getConnection();
        doDelete(args0,connection);
        Database.release(connection);
    } 

	public static void doDelete(BaseHistoryUsers args0, Connection connection)
	throws Exception{ 
        Statement statement = connection.createStatement();
        statement.executeUpdate("DELETE FROM HistoryUsers WHERE " + " id = " + Criteria.escape(args0.getId()) + "");
        statement.close();
        args0.saved = false; 	
    } 

	public static Scroller<HistoryUsers> doSelect(Criteria args0)
	throws Exception{ 
		return doSelect(args0.selectSQL("HISTORYUSERS.ID,HISTORYUSERS.COUNT","HISTORYUSERS"));
	} 

	public static Scroller<HistoryUsers> doSelect(String sql)
	throws Exception{         
        return new  HistoryUsersScroller(sql,false);
	} 

	public static Scroller<HistoryUsers> doSelect(Criteria args0, boolean recycle)
	throws Exception{ 
		return doSelect(args0.selectSQL("HISTORYUSERS.ID,HISTORYUSERS.COUNT","HISTORYUSERS"),recycle);
	} 

	public static Scroller<HistoryUsers> doSelect(String sql, boolean recycle)
	throws Exception{         
        return new  HistoryUsersScroller(sql,recycle);
	} 

	protected static HistoryUsers getBean(ResultSet results, HistoryUsers ret)
	throws Exception{ 

				ret.id=results.getInt("ID");
				ret.count=results.getLong("COUNT");
        
    
        ret.saved = true;        
                
        return ret;   
	} 


    private static class HistoryUsersScroller implements Scroller<HistoryUsers>{

        Statement statement;
        ResultSet results;   
        boolean recycle = false;  
        HistoryUsers cache = null;    

        private HistoryUsersScroller(String sql,boolean recycle) throws Exception{

            Connection connection = Database.getConnection();
            statement = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            results = statement.executeQuery(sql);
            Database.release(connection);
            this.recycle = recycle;
            
        }

        public HistoryUsers next(){        
            try{     
                cache = (recycle && cache != null)?  BaseHistoryUsersPeer.getBean(results, cache) : 
                                                     BaseHistoryUsersPeer.getBean(results, new HistoryUsers());
                return cache;
            }catch(Exception ignore){
                return null;
            }
        }

        public boolean hasNext(){
            try{
                if(results.next()){
                    return true;
                }else{
                    return false;   
                }
            }catch(Exception ignore){
                return false;
            }
        }

        public HistoryUsers previous(){        
            try{     
                cache = (recycle && cache != null)?  BaseHistoryUsersPeer.getBean(results, cache) : 
                                                     BaseHistoryUsersPeer.getBean(results, new HistoryUsers());
                return cache;
            }catch(Exception ignore){
                return null;
            }
        }

        public boolean hasPrevious(){
            try{
                if(results.previous()){
                    return true;
                }else{
                    return false;   
                }
            }catch(Exception ignore){
                return false;
            }
        }

        public void absolute(int position){
            try{results.absolute(position);}catch(Exception ignore){}    
        }

        public void remove() throws UnsupportedOperationException{ throw new UnsupportedOperationException(); }
        public int  size()   throws UnsupportedOperationException{ throw new UnsupportedOperationException(); }

        protected void finalize() throws Throwable{
            try{statement.close();}catch(Exception ignore){}
        }

    }


}
