package database;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * Autogenerated by Lisptorq 0.1.4
 */
public class FtpSiteInfo extends BaseFtpSiteInfo
{
    /**
     * 
     */
    private static final long serialVersionUID = -934469749691464459L;

    public static String SIMPLE_FORMAT_STRING = "%-20s%5d%15s%10s%15s%10d%5d";
    
    public static final short LS_ALR_RECURSIVE = 1;
    
    public static final short MANUAL_RECURSIVE= 0; 
    
    public static final short CAMPUS_SITE = 0;
    
    public static final short EDUCATION_SITE=1;
    
    public static final short WEB_SITE = 2;

    public String toString()
    {
	return new ToStringBuilder(this,ToStringStyle.DEFAULT_STYLE).append("server", server).append("username",username).toString();
	/*return this.getClass() + "[verify=" + verify + ",server=" + server
		+ ",port=" + port + ",username=" + username + ",password="
		+ password + ",encoding=" + encoding + ",contact=" + contact
		+ ",description=" + description + ",updateTime=" + updateTime
		+ ",lastUpdateTime=" + lastUpdateTime + ",totalFileCount="
		+ totalFileCount + ",crawlInterval=" + crawlInterval
		+ ",video=" + video + ",audio=" + audio + ",subtitle="
		+ subtitle + ",document=" + document + ",text=" + text
		+ ",program=" + program + ",image=" + image + ",compress="
		+ compress + ",executable=" + executable + ",directory="
		+ directory + ",unknown=" + unknown + "]";*/
    }
    public String getFtpAddressURL()
    {
	String portString = port == 21 ? "" : (":" + port);
	if (password != null && password.length() > 0)
	    return "ftp://" + username + ":" + password + "@" + server
		    + portString;
	else
	    return "ftp://" + username + "@" + server + portString;
    }

    public boolean equals(Object obj)
    {
	if (obj == null)
	    return false;
	if (!(obj instanceof BaseFtpSiteInfo))
	{
	    return false;
	}
	FtpSiteInfo ftpSite = (FtpSiteInfo) obj;
	return ftpSite.getServer().equals(this.server)
		&& ftpSite.getUsername().equals(ftpSite.getUsername());
    }

    public String getLocationString()
    {
	if (location==0)return new String("校园网");
	if (location==1)return new String("教育网");
	return new String("公共网");
    }
    
    public String getConnectString()
    {
	String connectString="ftp://"+this.getUsername()+":"+this.getPassword()+"@"+this.getAddress()+":"+this.getPort();
	return connectString;
    }
    public int hashCode()
    {
	if(this.server!=null)
	    return this.server.hashCode() + this.username.hashCode();
	else
	    return "null".hashCode()+this.username.hashCode();
    }
}