package database;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
/**
  * Autogenerated by Lisptorq 0.1.4 
*/
public class HistoryUsers extends BaseHistoryUsers
{ 
    /**
     * 
     */
    private static final long serialVersionUID = -3955074713844156045L;

    public String toString()
    {
	return ReflectionToStringBuilder.toString(this);
    }
}