package database;
/**
  * Autogenerated by Lisptorq 0.1.4 
*/
import java.sql.*;

public class BaseQueryStatisticsResultPeer  { 

	public static void doInsert(BaseQueryStatisticsResult args0)
	throws Exception{
        Connection connection = Database.getConnection(); 
        doSave(args0,false,connection);
        Database.release(connection);
	} 

	public static void doInsert(BaseQueryStatisticsResult args0,Connection connection)
	throws Exception{ 
        doSave(args0,false,connection);
	} 

	public static void doUpdate(BaseQueryStatisticsResult args0)
	throws Exception{ 	
        Connection connection = Database.getConnection(); 
        doSave(args0,true,connection);
        Database.release(connection);
    }

	public static void doUpdate(BaseQueryStatisticsResult args0,Connection connection)
	throws Exception{ 	
        doSave(args0,true,connection);
    }

	private static void doSave(BaseQueryStatisticsResult args0, boolean isUpdate, Connection connection)
	throws Exception{ 

        Statement statement = connection.createStatement();        
        String query = "";
        if(isUpdate){
            query = "UPDATE QueryStatisticsResult SET " + " keyword = " + Criteria.escape(args0.getKeyword()) + " , " + " frequency = " + Criteria.escape(args0.getFrequency()) + " WHERE ";
            statement.executeUpdate(query);
        }else{
            query = "INSERT INTO QueryStatisticsResult ( keyword , frequency ) VALUES ( " + Criteria.escape(args0.getKeyword()) + " , " + Criteria.escape(args0.getFrequency()) + " )";         
            statement.execute(query,Statement.RETURN_GENERATED_KEYS);
            ResultSet rs = statement.getGeneratedKeys();
            if(rs.next()){
                ;
            }
        }   
        statement.close();  
        args0.saved = true;      
	}
 
	public static void doDelete(Criteria args0)
	throws Exception{ 
        Connection connection = Database.getConnection();
        doDelete(args0,connection);
        Database.release(connection);
    } 

	public static void doDelete(Criteria args0, Connection connection)
	throws Exception{ 
        Statement statement = connection.createStatement();
        statement.executeUpdate(args0.deleteSQL("QUERYSTATISTICSRESULT"));
        statement.close();
    } 

	public static void doDelete(BaseQueryStatisticsResult args0)
	throws Exception{ 
        Connection connection = Database.getConnection();
        doDelete(args0,connection);
        Database.release(connection);
    } 

	public static void doDelete(BaseQueryStatisticsResult args0, Connection connection)
	throws Exception{ 
        Statement statement = connection.createStatement();
        statement.executeUpdate("DELETE FROM QueryStatisticsResult WHERE ");
        statement.close();
        args0.saved = false; 	
    } 

	public static Scroller doSelect(Criteria args0)
	throws Exception{ 
		return doSelect(args0.selectSQL("QUERYSTATISTICSRESULT.KEYWORD,QUERYSTATISTICSRESULT.FREQUENCY","QUERYSTATISTICSRESULT"));
	} 

	public static Scroller doSelect(String sql)
	throws Exception{         
        return new  QueryStatisticsResultScroller(sql,false);
	} 

	public static Scroller doSelect(Criteria args0, boolean recycle)
	throws Exception{ 
		return doSelect(args0.selectSQL("QUERYSTATISTICSRESULT.KEYWORD,QUERYSTATISTICSRESULT.FREQUENCY","QUERYSTATISTICSRESULT"),recycle);
	} 

	public static Scroller doSelect(String sql, boolean recycle)
	throws Exception{         
        return new  QueryStatisticsResultScroller(sql,recycle);
	} 

	protected static QueryStatisticsResult getBean(ResultSet results, QueryStatisticsResult ret)
	throws Exception{ 

				ret.keyword=results.getString("KEYWORD");
				ret.frequency=results.getInt("FREQUENCY");
        
    
        ret.saved = true;        
                
        return ret;   
	} 


    private static class QueryStatisticsResultScroller implements Scroller{

        Statement statement;
        ResultSet results;   
        boolean recycle = false;  
        QueryStatisticsResult cache = null;    

        private QueryStatisticsResultScroller(String sql,boolean recycle) throws Exception{

            Connection connection = Database.getConnection();
            statement = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            results = statement.executeQuery(sql);
            Database.release(connection);
            this.recycle = recycle;
            
        }

        public Object next(){        
            try{     
                cache = (recycle && cache != null)?  BaseQueryStatisticsResultPeer.getBean(results, cache) : 
                                                     BaseQueryStatisticsResultPeer.getBean(results, new QueryStatisticsResult());
                return cache;
            }catch(Exception ignore){
                return null;
            }
        }

        public boolean hasNext(){
            try{
                if(results.next()){
                    return true;
                }else{
                    return false;   
                }
            }catch(Exception ignore){
                return false;
            }
        }

        public Object previous(){        
            try{     
                cache = (recycle && cache != null)?  BaseQueryStatisticsResultPeer.getBean(results, cache) : 
                                                     BaseQueryStatisticsResultPeer.getBean(results, new QueryStatisticsResult());
                return cache;
            }catch(Exception ignore){
                return null;
            }
        }

        public boolean hasPrevious(){
            try{
                if(results.previous()){
                    return true;
                }else{
                    return false;   
                }
            }catch(Exception ignore){
                return false;
            }
        }

        public void absolute(int position){
            try{results.absolute(position);}catch(Exception ignore){}    
        }

        public void remove() throws UnsupportedOperationException{ throw new UnsupportedOperationException(); }
        public int  size()   throws UnsupportedOperationException{ throw new UnsupportedOperationException(); }

        protected void finalize() throws Throwable{
            try{statement.close();}catch(Exception ignore){}
        }

    }


}
