package database;
/**
  * Autogenerated by Lisptorq 0.1.4 
*/
import java.sql.*;

public class BaseQueryStatisticsPeer  { 

	public static void doInsert(BaseQueryStatistics args0)
	throws Exception{
        Connection connection = Database.getConnection(); 
        doSave(args0,false,connection);
        Database.release(connection);
	} 

	public static void doInsert(BaseQueryStatistics args0,Connection connection)
	throws Exception{ 
        doSave(args0,false,connection);
	} 

	public static void doUpdate(BaseQueryStatistics args0)
	throws Exception{ 	
        Connection connection = Database.getConnection(); 
        doSave(args0,true,connection);
        Database.release(connection);
    }

	public static void doUpdate(BaseQueryStatistics args0,Connection connection)
	throws Exception{ 	
        doSave(args0,true,connection);
    }

	private static void doSave(BaseQueryStatistics args0, boolean isUpdate, Connection connection)
	throws Exception{ 

        Statement statement = connection.createStatement();        
        String query = "";
        if(isUpdate){
            query = "UPDATE QueryStatistics SET " + " keyword = " + Criteria.escape(args0.getKeyword()) + " , " + " time = " + Criteria.escape(args0.getTime()) + " WHERE " + " id = " + Criteria.escape(args0.getId()) + "";
            statement.executeUpdate(query);
        }else{
            query = "INSERT INTO QueryStatistics ( keyword , time ) VALUES ( " + Criteria.escape(args0.getKeyword()) + " , " + Criteria.escape(args0.getTime()) + " )";         
            statement.execute(query,Statement.RETURN_GENERATED_KEYS);
            ResultSet rs = statement.getGeneratedKeys();
            if(rs.next()){
                args0.id=rs.getInt(1);
            }
        }   
        statement.close();  
        args0.saved = true;      
	}
 
	public static void doDelete(Criteria args0)
	throws Exception{ 
        Connection connection = Database.getConnection();
        doDelete(args0,connection);
        Database.release(connection);
    } 

	public static void doDelete(Criteria args0, Connection connection)
	throws Exception{ 
        Statement statement = connection.createStatement();
        statement.executeUpdate(args0.deleteSQL("QUERYSTATISTICS"));
        statement.close();
    } 

	public static void doDelete(BaseQueryStatistics args0)
	throws Exception{ 
        Connection connection = Database.getConnection();
        doDelete(args0,connection);
        Database.release(connection);
    } 

	public static void doDelete(BaseQueryStatistics args0, Connection connection)
	throws Exception{ 
        Statement statement = connection.createStatement();
        statement.executeUpdate("DELETE FROM QueryStatistics WHERE " + " id = " + Criteria.escape(args0.getId()) + "");
        statement.close();
        args0.saved = false; 	
    } 

	public static Scroller doSelect(Criteria args0)
	throws Exception{ 
		return doSelect(args0.selectSQL("QUERYSTATISTICS.ID,QUERYSTATISTICS.KEYWORD,QUERYSTATISTICS.TIME","QUERYSTATISTICS"));
	} 

	public static Scroller doSelect(String sql)
	throws Exception{         
        return new  QueryStatisticsScroller(sql,false);
	} 

	public static Scroller doSelect(Criteria args0, boolean recycle)
	throws Exception{ 
		return doSelect(args0.selectSQL("QUERYSTATISTICS.ID,QUERYSTATISTICS.KEYWORD,QUERYSTATISTICS.TIME","QUERYSTATISTICS"),recycle);
	} 

	public static Scroller doSelect(String sql, boolean recycle)
	throws Exception{         
        return new  QueryStatisticsScroller(sql,recycle);
	} 

	protected static QueryStatistics getBean(ResultSet results, QueryStatistics ret)
	throws Exception{ 

				ret.id=results.getInt("ID");
				ret.keyword=results.getString("KEYWORD");
				ret.time=results.getDate("TIME");
        
    
        ret.saved = true;        
                
        return ret;   
	} 


    private static class QueryStatisticsScroller implements Scroller{

        Statement statement;
        ResultSet results;   
        boolean recycle = false;  
        QueryStatistics cache = null;    

        private QueryStatisticsScroller(String sql,boolean recycle) throws Exception{

            Connection connection = Database.getConnection();
            statement = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            results = statement.executeQuery(sql);
            Database.release(connection);
            this.recycle = recycle;
            
        }

        public Object next(){        
            try{     
                cache = (recycle && cache != null)?  BaseQueryStatisticsPeer.getBean(results, cache) : 
                                                     BaseQueryStatisticsPeer.getBean(results, new QueryStatistics());
                return cache;
            }catch(Exception ignore){
                return null;
            }
        }

        public boolean hasNext(){
            try{
                if(results.next()){
                    return true;
                }else{
                    return false;   
                }
            }catch(Exception ignore){
                return false;
            }
        }

        public Object previous(){        
            try{     
                cache = (recycle && cache != null)?  BaseQueryStatisticsPeer.getBean(results, cache) : 
                                                     BaseQueryStatisticsPeer.getBean(results, new QueryStatistics());
                return cache;
            }catch(Exception ignore){
                return null;
            }
        }

        public boolean hasPrevious(){
            try{
                if(results.previous()){
                    return true;
                }else{
                    return false;   
                }
            }catch(Exception ignore){
                return false;
            }
        }

        public void absolute(int position){
            try{results.absolute(position);}catch(Exception ignore){}    
        }

        public void remove() throws UnsupportedOperationException{ throw new UnsupportedOperationException(); }
        public int  size()   throws UnsupportedOperationException{ throw new UnsupportedOperationException(); }

        protected void finalize() throws Throwable{
            try{statement.close();}catch(Exception ignore){}
        }

    }


}
