/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.form;

import org.apache.struts.validator.ValidatorForm;

import database.Article;

/**
 * MyEclipse Struts Creation date: 09-22-2008 XDoclet definition:
 * 
 * @struts.form name="modifyMessageForm"
 */
public class ArticleUpdateForm extends ValidatorForm
{
    /*
     * Generated fields
     */

    /**
	 * 
	 */
    private static final long serialVersionUID = -5301825140246590432L;

    /** article property */
    private Article article = new Article();
    private String type;
    /*
     * Generated Methods
     */

    /**
     * Returns the article.
     * 
     * @return Article
     */
    public Article getArticle()
    {
	return article;
    }

    /**
     * Set the article.
     * 
     * @param article
     *            The article to set
     */
    public void setArticle(Article article)
    {
	this.article = article;
    }

    public String getType()
    {
        return type;
    }

    public void setType(String type)
    {
        this.type = type;
    }
}