/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.form;

import org.apache.struts.validator.ValidatorForm;

import database.Article;

/**
 * MyEclipse Struts Creation date: 09-22-2008 XDoclet definition:
 * 
 * @struts.form name="newMessageForm"
 */
public class ArticleNewForm extends ValidatorForm
{
    /*
     * Generated fields
     */

    /**
	 * 
	 */
    private static final long serialVersionUID = 2832611057802363243L;

    /** articles property */
    private Article article = new Article();

    private String verifyConfirm;

    public ArticleNewForm()
    {
	// article.setContent("what's wrong");
    }

    /*
     * Generated Methods
     */

    public String getVerifyConfirm()
    {
	return verifyConfirm;
    }

    public void setVerifyConfirm(String verifyConfirm)
    {
	this.verifyConfirm = verifyConfirm;
    }

    // /*
    // *
    // *//**
    // * Method validate
    // * @param mapping
    // * @param request
    // * @return ActionErrors
    // */
    // public ActionErrors validate(ActionMapping mapping,
    // HttpServletRequest request) {
    // ActionErrors ae = super.validate(mapping, request);
    // System.out.println(ae+"\n verifyConfirm="+verifyConfirm);
    //		
    // return ae;
    // }
    //
    // /**
    // * Method reset
    // * @param mapping
    // * @param request
    // */
    // public void reset(ActionMapping mapping, HttpServletRequest request) {
    // }

    /**
     * Returns the articles.
     * 
     * @return Articles
     */
    public Article getArticle()
    {
	return article;
    }

    /**
     * Set the articles.
     * 
     * @param articles
     *            The articles to set
     */
    public void setArticle(Article article)
    {
	this.article = article;
    }
}