/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.form;

import org.apache.struts.validator.ValidatorForm;

import database.FtpSiteInfo;

/**
 * MyEclipse Struts Creation date: 03-10-2008 XDoclet definition:
 * 
 * @struts.form name="regFtpSiteForm"
 */
public class FtpSiteRegForm extends ValidatorForm
{
    /*
     * Generated fields
     */

    /**
	 * 
	 */
    private static final long serialVersionUID = -7483145179775149430L;

    private FtpSiteInfo ftpSiteInfo = new FtpSiteInfo();

    private String verifyConfirm;

    public FtpSiteInfo getFtpSiteInfo()
    {
	return this.ftpSiteInfo;
    }

    public void setFtpSiteInfo(FtpSiteInfo ftpSiteInfo)
    {
	this.ftpSiteInfo = ftpSiteInfo;
    }

    public void setVerifyConfirm(String verifyConfirm)
    {
	this.verifyConfirm = verifyConfirm;
    }

    public String getVerifyConfirm()
    {
	return this.verifyConfirm;
    }
}