package database;

import java.io.Serializable;

/**
  * Autogenerated by Lisptorq 0.1.4 
*/
public class BaseSessions   implements Serializable{ 
	/**
     * 
     */
    private static final long serialVersionUID = -3372282559213250580L;
	public static final String DESTROYTIME  = "SESSIONS.DESTROYTIME"; 
	public static final String ID  = "SESSIONS.ID"; 
	protected long destroyTime; 
	protected int id; 
	protected long createTime; 
	protected boolean saved  = false; 
	public static final String CREATETIME  = "SESSIONS.CREATETIME"; 

	public void save()
	throws Exception{ 
		if(saved){
			BaseSessionsPeer.doUpdate(this);
		}else{
			BaseSessionsPeer.doInsert(this);
		}
	} 

	public long getCreateTime(){ 
		return createTime;
	} 

	public void setDestroyTime(long args0){ 
		destroyTime =args0;
	} 

	public long getDestroyTime(){ 
		return destroyTime;
	} 

	/**
	  * id is autogenerated 
	*/
	public int getId(){ 
		return id;
	} 

	public void setCreateTime(long args0){ 
		createTime =args0;
	} 
}