package database;

/**
  * Autogenerated by Lisptorq 0.1.4 
*/
import java.io.Serializable;
import java.sql.*;
public class BaseResponsePost implements Serializable  { 
	/**
     * 
     */
    private static final long serialVersionUID = -8589313327806347796L;
	public static final String VERIFY  = "RESPONSEPOST.VERIFY"; 
	public static final String TIME  = "RESPONSEPOST.TIME"; 
	public static final String AUTHOR  = "RESPONSEPOST.AUTHOR"; 
	public static final String POSTID  = "RESPONSEPOST.POSTID"; 
	protected String verify; 
	protected Timestamp time; 
	protected String author  = "anonymous"; 
	protected int id; 
	protected int postid; 
	protected Article _article  = null; 
	protected String content; 
	protected String ip; 
	protected boolean saved  = false; 
	public static final String ID  = "RESPONSEPOST.ID"; 
	public static final String CONTENT  = "RESPONSEPOST.CONTENT"; 
	public static final String IP  = "RESPONSEPOST.IP"; 

	public void save()
	throws Exception{ 
		if(saved){
			BaseResponsePostPeer.doUpdate(this);
		}else{
			BaseResponsePostPeer.doInsert(this);
		}
	} 

	public String getIp(){ 
		return ip;
	} 

	public String getContent(){ 
		return content;
	} 

	public int getId(){ 
		return id;
	} 

	public String getAuthor(){ 
		return author;
	} 

	public Timestamp getTime(){ 
		return time;
	} 

	public String getVerify(){ 
		return verify;
	} 

	public void setArticle(Article args0){ 
		_article=args0;
		id=args0.getId();
	} 

	public void setId(int args0){ 
		_article=null;
		id=args0;
	} 

	public Article getArticle(){ 

        if(_article != null) return _article;

        try{        

            Criteria crit = new Criteria();
            crit.add(Article.ID,id);
            Scroller<Article> iter = BaseArticlePeer.doSelect(crit);
            if(iter.hasNext()){
              _article = iter.next();
              return _article;
            }
     
        }catch(Exception ignore){}
        
        return null;
	} 

	public void setVerify(String args0){ 
		verify =args0;
	} 

	public void setTime(Timestamp args0){ 
		time =args0;
	} 

	public void setAuthor(String args0){ 
		author =args0;
	} 

	/**
	  * postid is autogenerated 
	*/
	public int getPostid(){ 
		return postid;
	} 

	public void setContent(String args0){ 
		content =args0;
	} 

	public void setIp(String args0){ 
		ip =args0;
	} 
}