package database;

import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

/**
 * Autogenerated by Lisptorq 0.1.4
 */
public class BaseQueryStatisticsResult implements Serializable
{
    /**
     * 
     */
    private static final long serialVersionUID = 5999190750316593655L;

    public static final String FREQUENCY = "QUERYSTATISTICSRESULT.FREQUENCY";

    protected boolean saved = false;

    protected String keyword;

    protected int frequency;

    public static final String KEYWORD = "QUERYSTATISTICSRESULT.KEYWORD";

    public void save() throws Exception
    {
	if (saved)
	{
	    BaseQueryStatisticsResultPeer.doUpdate(this);
	}
	else
	{
	    BaseQueryStatisticsResultPeer.doInsert(this);
	}
    }

    public String getKeyword()
    {
	return keyword;
    }

    public int getFrequency()
    {
	return frequency;
    }

    // zhonghua Add encoding
    public String getEncodedKeyword() throws UnsupportedEncodingException
    { 
	return URLEncoder.encode(keyword,"utf-8");
    }
    public void setFrequency(int args0)
    {
	frequency = args0;
    }

    public void setKeyword(String args0)
    {
	keyword = args0;
    }
}