package database;

/**
  * Autogenerated by Lisptorq 0.1.4 
*/
import java.io.Serializable;
import java.sql.*;
public class BaseArticle  implements Serializable { 
	/**
     * 
     */
    private static final long serialVersionUID = 4389770277338171755L;
	public static final String VERIFY  = "ARTICLE.VERIFY"; 
	public static final String CLICKCOUNT  = "ARTICLE.CLICKCOUNT"; 
	public static final String TITLE  = "ARTICLE.TITLE"; 
	public static final String AUTHOR  = "ARTICLE.AUTHOR"; 
	protected boolean saved  = false; 
	protected String ip; 
	protected String content; 
	protected Timestamp time; 
	protected int id; 
	protected String author  = "anonymous"; 
	protected String title; 
	protected int clickcount = 0; 
	protected String verify; 
	public static final String ID  = "ARTICLE.ID"; 
	public static final String TIME  = "ARTICLE.TIME"; 
	public static final String CONTENT  = "ARTICLE.CONTENT"; 
	public static final String IP  = "ARTICLE.IP"; 

	public void save()
	throws Exception{ 
		if(saved){
			BaseArticlePeer.doUpdate(this);
		}else{
			BaseArticlePeer.doInsert(this);
		}
	} 

	public String getIp(){ 
		return ip;
	} 

	public String getContent(){ 
		return content;
	} 

	public Timestamp getTime(){ 
		return time;
	} 

	public void setAuthor(String args0){ 
		author =args0;
	} 

	public void setTitle(String args0){ 
		title =args0;
	} 

	public void setClickcount(int args0){ 
		clickcount =args0;
	} 

	public void setVerify(String args0){ 
		verify =args0;
	} 

	public String getVerify(){ 
		return verify;
	} 

	public int getClickcount(){ 
		return clickcount;
	} 

	public String getTitle(){ 
		return title;
	} 

	public String getAuthor(){ 
		return author;
	} 

	/**
	  * id is autogenerated 
	*/
	public int getId(){ 
		return id;
	} 

	public void setTime(Timestamp args0){ 
		time =args0;
	} 

	public void setContent(String args0){ 
		content =args0;
	} 

	public void setIp(String args0){ 
		ip =args0;
	} 
}