package database;

/**
  * Autogenerated by Lisptorq 0.1.4 
*/
import java.io.Serializable;
import java.sql.*;
public class BaseQueryStatistics  implements Serializable  { 
	/**
     * 
     */
    private static final long serialVersionUID = -8500313486065358492L;
	public static final String HITS  = "QUERYSTATISTICS.HITS"; 
	public static final String KEYWORD  = "QUERYSTATISTICS.KEYWORD"; 
	protected boolean saved  = false; 
	protected Timestamp time; 
	protected int id; 
	protected String keyword; 
	protected int hits; 
	public static final String ID  = "QUERYSTATISTICS.ID"; 
	public static final String TIME  = "QUERYSTATISTICS.TIME"; 

	public void save()
	throws Exception{ 
		if(saved){
			BaseQueryStatisticsPeer.doUpdate(this);
		}else{
			BaseQueryStatisticsPeer.doInsert(this);
		}
	} 

	public Timestamp getTime(){ 
		return time;
	} 

	public void setKeyword(String args0){ 
		keyword =args0;
	} 

	public void setHits(int args0){ 
		hits =args0;
	} 

	public int getHits(){ 
		return hits;
	} 

	public String getKeyword(){ 
		return keyword;
	} 

	/**
	  * id is autogenerated 
	*/
	public int getId(){ 
		return id;
	} 

	public void setTime(Timestamp args0){ 
		time =args0;
	} 
}