package database;

import java.io.Serializable;

/**
  * Autogenerated by Lisptorq 0.1.4 
*/
public class BaseHistoryUsers  implements Serializable
{ 
	/**
     * 
     */
    private static final long serialVersionUID = -8665841589979472337L;
	public static final String COUNT  = "HISTORYUSERS.COUNT"; 
	protected boolean saved  = false; 
	protected int id; 
	protected long count; 
	public static final String ID  = "HISTORYUSERS.ID"; 

	public void save()
	throws Exception{ 
		if(saved){
			BaseHistoryUsersPeer.doUpdate(this);
		}else{
			BaseHistoryUsersPeer.doInsert(this);
		}
	} 

	public void setCount(long args0){ 
		count =args0;
	} 

	public long getCount(){ 
		return count;
	} 

	/**
	  * id is autogenerated 
	*/
	public int getId(){ 
		return id;
	} 
}