package database;

/**
 * Autogenerated by Lisptorq 0.1.4 from derby-connection.template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Stack;

import resource.CrawlerSetting;

public class Database
{

    private static Stack<Connection> _pool = new Stack<Connection>();

    private static final String url = CrawlerSetting
	    .getProperty("database.url");

    private static final String username = CrawlerSetting
	    .getProperty("database.username");

    private static final String password = CrawlerSetting
	    .getProperty("database.password");

    private static final String driver = CrawlerSetting
	    .getProperty("database.driver");
    static
    {

	try
	{

	    Class.forName(driver);
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
    }

    public static Connection getConnection() throws SQLException
    {
//	try
//	{
	    synchronized (_pool)
	    {
		if (!_pool.empty())
		{
		    return  (Connection) _pool.pop();
		}
	    }

	    return DriverManager.getConnection(url, username, password);
//	}
//	catch (Exception e)
//	{
//	    e.printStackTrace();
//	}
//	return null;
    }

    protected Connection getCreationConnection() throws Exception
    {
	return DriverManager.getConnection(url, username, password);
    }

    public static void shutdown()
    {
	try
	{
	    synchronized (_pool)
	    {
		while (!_pool.empty())
		{
		    try
		    {
			Connection conn = (Connection) _pool.pop();
			conn.close();
		    }
		    catch (Exception ignore)
		    {
		    }
		}
	    }

	}
	catch (Exception ex)
	{
	    System.out.println("Shutting down sql server: " + ex.getMessage());
	}
    }

    public static void release(Connection connection)
    {
	synchronized (_pool)
	{
	    try
	    {
		connection.setAutoCommit(true);
	    }
	    catch (Exception ignore)
	    {
	    }
	    _pool.push(connection);
	}
    }

}
