package database;

/**
 * Autogenerated by Lisptorq 0.1.4
 */
import java.sql.Connection;
import java.sql.Statement;

public class FtpSiteInfoPeer extends BaseFtpSiteInfoPeer
{
    public static void doDeleteAll() throws Exception
    {
	Connection connection = Database.getConnection();
	Statement statement = connection.createStatement();
	statement.executeUpdate("DELETE FROM FtpSiteInfo");
	statement.close();
	Database.release(connection);
    }
    public static int TotalFtpSitesNumber() throws Exception
    {
	Criteria c = new Criteria();
	Scroller<FtpSiteInfo> scr = FtpSiteInfoPeer.doSelect(c);
	return scr.size();
    }  
    
    public static void main(String[] args)
    {
	try
	{
	    Criteria c = new Criteria();
	    // c.addAscendingOrder("server");
	    Scroller<FtpSiteInfo> scr = FtpSiteInfoPeer.doSelect(c);
	    if (!scr.hasNext())
	    {
		System.out.println("Empty");
	    }
	    while (scr.hasNext())
	    {
		FtpSiteInfo info = (FtpSiteInfo) scr.next();
		System.out.println(info);
	    }
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
    }
}