package database;



/**
 * Autogenerated by Lisptorq 0.1.4
 */
public class QueryStatisticsResult extends BaseQueryStatisticsResult
{


    /**
     * 
     */
    private static final long serialVersionUID = 1059751248591847927L;

    public String toString()
    {
	return this.getClass().toString() + "[keyword=" + this.keyword
		+ ", frequency=" + this.frequency + "]";
    }
}