package database;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;


/**
 * Autogenerated by Lisptorq 0.1.4
 */
public class QueryStatistics extends BaseQueryStatistics
{
    /**
     * 
     */
    private static final long serialVersionUID = -2372103315541119102L;

    public String toString()
    {
	return ReflectionToStringBuilder.toString(this);
    }
}