package database;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

/**
  * Autogenerated by Lisptorq 0.1.4 
*/
public class ResourceRequest extends BaseResourceRequest { 
    
    /**
     * 
     */
    private static final long serialVersionUID = -7784490688619125457L;
    public static final short NOT_ANSWERED= 0;
    public static final short ANSWERED = 1;
    public String toString()
    {
	return ReflectionToStringBuilder.toString(this);
    }
    public String getStateString()
    {
	if(state==0) return "未回复";
	return "已回复";
    }
}