package database;

import java.net.UnknownHostException;

/**
  * Autogenerated by Lisptorq 0.1.4 
*/
public class ResponsePostPeer extends BaseResponsePostPeer { 
    public static String updateResponsePost(ResponsePost responsePost)
    {
	try
	    {
		Criteria c = new Criteria();
		c.add(ResponsePost.ID, responsePost.getId());
		c.add(ResponsePost.VERIFY, responsePost.getVerify());
		Scroller<ResponsePost> scr = ResponsePostPeer.doSelect(c);
		if (!scr.hasNext())
		{
		    return "Verify incorrect";
		}
		responsePost.save();
		return null;
	    }
	    catch (UnknownHostException e)
	    {
		e.printStackTrace();
		return e.getMessage();
	    }
	    catch (Exception e)
	    {
		e.printStackTrace();
		return e.getMessage();
	    }
    }
    public static String deleteResponsePost(ResponsePost responsePost)
    {
	try
	    {
		Criteria c = new Criteria();
		c.add(ResponsePost.ID, responsePost.getId());
		c.add(ResponsePost.VERIFY, responsePost.getVerify());
		Scroller<ResponsePost> scr = ResponsePostPeer.doSelect(c);
		if (!scr.hasNext())
		{
		    return "Verify incorrect";
		}
		ResponsePostPeer.doDelete(c);
		return null;
	    }
	    catch (UnknownHostException e)
	    {
		e.printStackTrace();
		return e.getMessage();
	    }
	    catch (Exception e)
	    {
		e.printStackTrace();
		return e.getMessage();
	    }
    }
}