package database;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

/**
  * Autogenerated by Lisptorq 0.1.4 
*/
public class ResponsePost extends BaseResponsePost
{   
    /**
     * 
     */
    private static final long serialVersionUID = 1371827950881399365L;

    public String toString()
    {
	return ReflectionToStringBuilder.toString(this);
    }
}