package database;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

/**
  * Autogenerated by Lisptorq 0.1.4 
*/
public class Sessions extends BaseSessions
{
    /**
     * 
     */
    private static final long serialVersionUID = -1744805760873538348L;

    public String toString()
    {
	return ReflectionToStringBuilder.toString(this);
    }
}