/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessages;

import cn.askrosa.struts.form.ArticleResponsePostForm;

import database.ResponsePost;

/**
 * MyEclipse Struts Creation date: 09-23-2008 XDoclet definition:
 * 
 * @struts.action path="/submitResponsePost" name="submitResponsePostForm"
 *                input="/submitResponsePost.jsp" scope="request"
 *                validate="true"
 * @struts.action-forward name="success" path="/inforOutput.jsp"
 */
public class ArticleResponsePostDoAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	ArticleResponsePostForm articleResponsePostForm = (ArticleResponsePostForm) form;
	ActionMessages errors= articleResponsePostForm.validate(mapping, request);
	if(!errors.isEmpty())
	{
	    this.saveErrors(request, errors);
	    ActionForward af=new ActionForward("/articleShow.do?id="+articleResponsePostForm.getId());
	    return af;
	} 
	try
	{    
	    ResponsePost responsePost = articleResponsePostForm.getResponsePost();
	    responsePost.setIp(request.getRemoteAddr());
	    responsePost.setId(Integer.parseInt(request.getParameter("id")));
	    responsePost.save();
	    request.setAttribute("infor", "回帖成功");
	    request.setAttribute("forward", "查看留言");
	    request.setAttribute("forwarddo", "articleShow.do?id=" + responsePost.getId());
	    return mapping.findForward("success");
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
	return mapping.getInputForward();
    }
}