/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.askrosa.struts.form.ArticleResponsePostUpdateForm;

import database.Criteria;
import database.ResponsePost;
import database.ResponsePostPeer;
import database.Scroller;

/**
 * MyEclipse Struts Creation date: 09-23-2008 XDoclet definition:
 * 
 * @struts.action path="/modifyResponsePost" name="updateResponsePostForm"
 * @struts.action-forward name="success" path="/updateResponsePost.jsp"
 */
public class ArticleResponsePostUpdateAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	ArticleResponsePostUpdateForm updateResponsePostForm = (ArticleResponsePostUpdateForm) form;
	String id = request.getParameter("id");

	if (id != null)
	{
	    try
	    {
		Criteria crit = new Criteria();
		crit.add(ResponsePost.POSTID, id.trim());
		Scroller<ResponsePost> results = ResponsePostPeer.doSelect(crit);
		if (!results.hasNext())
		    return mapping.getInputForward();
		ResponsePost responsePost = results.next();
		responsePost.setVerify("");
		updateResponsePostForm.setResponsePost(responsePost);	
		HttpSession session = request.getSession();
		session.setAttribute("title", "回帖修改");
		ActionForward af = mapping.findForward("success");
		return af;
	    }
	    catch (Exception ignore)
	    {
		ignore.printStackTrace();
	    }
	}

	return mapping.getInputForward();
    }
}