/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import resource.WebSetting;
import cn.askrosa.struts.form.ArticleResponsePostUpdateForm;
import database.ResponsePost;
import database.ResponsePostPeer;

/**
 * MyEclipse Struts Creation date: 09-23-2008 XDoclet definition:
 * 
 * @struts.action path="/updateResponsePost" name="updateResponsePostForm"
 *                input="/updateResponsePost.jsp" validate="true"
 * @struts.action-forward name="success" path="/inforOutput.jsp"
 */
public class ArticleResponsePostUpdateDoAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	ArticleResponsePostUpdateForm updateResponsePostForm = (ArticleResponsePostUpdateForm) form;// TODO
	// Auto-generated
	// method
	// stub
	ResponsePost responsePost = updateResponsePostForm.getResponsePost();
	responsePost.setIp(request.getRemoteAddr());
	int articleId = responsePost.getId();
	String type = updateResponsePostForm.getType();
	try
	{
	    if (type.equals(WebSetting.getProperty("ftpsearch.jsp.updateftpsite.type.update")))
	    {
		String ret = ResponsePostPeer.updateResponsePost(responsePost);
		if (ret == null)
		{
		    request.setAttribute("infor", "留言修改成功");
		    request.setAttribute("forward", "查看留言");
		    request.setAttribute("forwarddo", "articleShow.do?id=" + articleId);
		    return mapping.findForward("success");
		}
		else
		{
		    ActionMessages errors = new ActionMessages();
		    errors.add("responsePost.verify", new ActionMessage(ret, false));
		    saveErrors(request, errors);
		    return mapping.getInputForward();
		}
	    }
	    else if (type.equals(WebSetting.getProperty("ftpsearch.jsp.updateftpsite.type.delete")))
	    {
		String ret = ResponsePostPeer.deleteResponsePost(responsePost);
		if (ret == null)
		{
		    request.setAttribute("infor", "回贴删除成功");
		    request.setAttribute("forward", "查看回贴对应的留言");
		    request.setAttribute("forwarddo", "articleShow.do?id=" + articleId);
		    return mapping.findForward("success");
		}
		else
		{
		    ActionMessages errors = new ActionMessages();
		    errors.add("responsePost.verify", new ActionMessage(ret, false));
		    saveErrors(request, errors);
		    return mapping.getInputForward();
		}
	    }
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
	return null;
    }
}