/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import java.util.Iterator;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.askrosa.others.NumberFormat;

import searcher.FtpSearch;

/**
 * MyEclipse Struts Creation date: 04-09-2009 XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class AutoCompleteAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	String q = request.getParameter("q");
	try
	{
	    Map<String, Integer> ret = FtpSearch.suggestSimilar(q);
	    response.getWriter().write("[");
	    int size = ret.size();
	    Iterator<String> ite = ret.keySet().iterator();
	    //System.out.println("****************"+q+",size:"+size);
	    if (ite.hasNext())
	    {
		for (int i = 0; i < size - 1; i++)
		{
		    String key = ite.next();
		    int hits = ret.get(key);
		    String hitsString=NumberFormat.numberFormat(hits);
		    response.getWriter().write("{text:'" + key + "', content:'约 " + hitsString + " 结果'},");
		}
		String key = ite.next();
		int hits = ret.get(key);
		String hitsString=NumberFormat.numberFormat(hits);
		response.getWriter().write("{text:'" + key + "', content:'约 " + hitsString + " 结果'}]");
	    }
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
	return null;
    }
}