/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import java.io.File;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import cn.askrosa.struts.form.FtpSiteRegForm;

import database.FtpSitesManager;
import database.FtpSiteInfo;

/**
 * MyEclipse Struts Creation date: 03-10-2008 XDoclet definition:
 * 
 * @struts.action path="/regFtpSite" name="regFtpSiteForm"
 *                input="regFtpSite.jsp" scope="request" validate="true"
 */
public class FtpSiteRegAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	FtpSiteRegForm regFtpSiteForm = (FtpSiteRegForm) form;
	FtpSiteInfo ftpSite = regFtpSiteForm.getFtpSiteInfo();
	String ret = FtpSitesManager.addFtpSiteWithoutCheck(ftpSite);
	if (ret != null)
	{
	    ActionMessages errors = new ActionMessages();
	    errors.add("ftpSiteInfo.server", new ActionMessage(ret, false));
	    saveErrors(request, errors);
	    return mapping.getInputForward();
	}
	String path = this.getServlet().getServletContext().getRealPath("/")
		+ "/XMLForFlashFxp.ftp";
	try
	{
	    FtpSitesManager.storeFtpSitesToXML(new File(path));
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
	request.setAttribute("infor", "增加ftp站点操作成功");
	request.setAttribute("forward", "查看ftp列表");
	request.setAttribute("forwarddo", "ftpSiteList.do");
	return mapping.findForward("success");
    }
}