/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import database.Criteria;
import database.ResourceRequest;
import database.ResourceRequestPeer;
import database.Scroller;


/**
 * MyEclipse Struts Creation date: 03-07-2009 XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class ResourceRequestDeleteAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	// TODO Auto-generated method stub
	String id = request.getParameter("id");
	int idInt=Integer.parseInt(id.trim());
	String email = request.getParameter("email");	
	try
	{
	    Criteria c = new Criteria();
	    c.add(ResourceRequest.ID, idInt);
	    c.add(ResourceRequest.EMAIL,email);
	    Scroller<ResourceRequest> results = ResourceRequestPeer.doSelect(c);
	    if (!results.hasNext())
	    {
		request.setAttribute("infor", "email地址不符");
		ActionForward af=new ActionForward("/inforOutputJS.jsp");
		return af;
	    }		
	    ResourceRequestPeer.doDelete(c);
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
	request.setAttribute("infor", "删除资源请求操作成功");
	request.setAttribute("forward", "查看资源请求列表");
	request.setAttribute("forwarddo", "resourceRequestList.do?page=1");
	return mapping.findForward("success");
    }
}