/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import searcher.FtpSearch;
import searcher.SearchParameter;
import searcher.SearchResult;

import cn.askrosa.struts.form.ResourceRequestForm;

/**
 * MyEclipse Struts Creation date: 07-20-2008 XDoclet definition:
 * 
 * @struts.action path="/resourceRequest" name="resourceRequestForm"
 *                input="resourceRequest.jsp" scope="request" validate="true"
 */
public class ResourceRequestAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	ResourceRequestForm resourceRequestForm = (ResourceRequestForm) form;
	String keyword = resourceRequestForm.getRequest().getResourcename();
	SearchParameter parameter = new SearchParameter();
	parameter.setKeyword(keyword);
	parameter.setBegin(0);
	parameter.setCount(1);
	
	SearchResult res;
	try
	{
	    res = FtpSearch.search(parameter, false);
	    if (res.getResultFileList().size() != 0)
	    {
		request.setAttribute("infor", "资源搜索的结果不为零，请输入更精确的关键字！");
		ActionForward af = new ActionForward("/inforOutputJS.jsp");
		return af;
	    }
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}

	String deadline = resourceRequestForm.getDeadline();
	SimpleDateFormat bartDateFormat = new SimpleDateFormat("yyyyMMdd");
	java.util.Calendar deadlineCalendar = java.util.Calendar.getInstance();
	java.sql.Date deadlineDateSql;
	try
	{
	    if (deadline == null || deadline.equals(""))
	    {
		long addtime=30;
		addtime*=24;
		addtime*=3600000;
		deadlineDateSql = new java.sql.Date(deadlineCalendar.getTimeInMillis()+ addtime);
	    }
	    else
	    {
		deadlineCalendar.setTime(bartDateFormat.parse(deadline));
	        deadlineDateSql = new java.sql.Date(deadlineCalendar.getTimeInMillis());
	    }
	    resourceRequestForm.getRequest().setDeadline(deadlineDateSql);
	}
	catch (ParseException e1)
	{
	    e1.printStackTrace();
	}
	try
	{
	    resourceRequestForm.getRequest().save();
	    request.setAttribute("infor", "资源请求成功，我们已记录你的请求！");
	    request.setAttribute("forward", "查看请求列表");
	    request.setAttribute("forwarddo", "resourceRequestList.do");
	    return mapping.findForward("success");
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
	return null;
    }
}