/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import cn.askrosa.others.PageIndexResult;
import cn.askrosa.struts.form.ResourceRequestListForm;
import database.ResourceRequest;
import database.ResourceRequestPeer;
import database.Scroller;

/**
 * MyEclipse Struts Creation date: 09-28-2008 XDoclet definition:
 * 
 * @struts.action
 * @struts.action-forward name="success" path="listResourceRequest.jsp"
 */
public class ResourceRequestListAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     * @throws Exception
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response) throws Exception
    {
	ResourceRequestListForm resourceRequestListForm = (ResourceRequestListForm) form;
	String resoureName = resourceRequestListForm.getKeyword();
	String dateFrom = resourceRequestListForm.getDateFrom();
	String dateTo = resourceRequestListForm.getDateTo();
	String pageString = request.getParameter("page");
	short state = resourceRequestListForm.getState();
	
	final int pageSize = 30;
	int pageDisplayNumber =15;
	String sort = request.getParameter("sort");
	if (pageString==null)
	    pageString = "1";
	int page = Integer.parseInt(pageString);
	int from = (page - 1) * pageSize;
	
	Scroller<ResourceRequest> srcSize = ResourceRequestPeer.listPagedResourceRequest(resoureName,dateFrom,dateTo,sort,state);	
	int resultNumber=srcSize.size();
	
	request.setAttribute("listing", ResourceRequestPeer.listPagedResourceRequest(resoureName,from,pageSize,dateFrom,dateTo,sort,state));
	int resultPages = (int) Math.ceil( resultNumber / (double) pageSize);		
	request.setAttribute("page", (page-1)*pageSize);
	request.setAttribute("title", "资源请求列表");
	request.setAttribute("pageIndex", PageIndexResult.getPageIndexResult(page,
		pageDisplayNumber, resultPages,"resourceRequestList.do?page="));
	return new ActionForward(mapping.findForward("success"));
    }
}