/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.askrosa.struts.form.ArticleNewForm;

import database.Article;

/**
 * MyEclipse Struts Creation date: 09-22-2008 XDoclet definition:
 * 
 * @struts.action path="/newMessage" name="newMessageForm"
 *                input="/newMessage.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/listArticles.do"
 */
public class ArticleNewAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	ArticleNewForm newMessageForm = (ArticleNewForm) form;
	try
	{
	    Article article = newMessageForm.getArticle();
	    article.setIp(request.getRemoteAddr());
	    article.save();
	    request.setAttribute("infor", "留言成功");
	    request.setAttribute("forward", "查看留言列表");
	    request.setAttribute("forwarddo", "articleList.do?sort=id&page=1");
	    return mapping.findForward("success");
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
	return mapping.getInputForward();
    }
}