/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import database.Article;
import database.ArticlePeer;
import database.Criteria;
import database.ResponsePost;
import database.ResponsePostPeer;
import database.Scroller;

/**
 * MyEclipse Struts Creation date: 09-22-2008 XDoclet definition:
 * 
 * @struts.action path="/showArticle" name="showArticleForm" scope="request"
 * @struts.action-forward name="success" path="/showArticle.jsp"
 */
public class ArticleShowAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	String id = request.getParameter("id");
	if (id != null)
	{
	    try
	    {
		// get Contact by Id
		HttpSession session = request.getSession();
		session.setAttribute("articleId", id);

		Criteria crit = new Criteria();
		crit.add(ResponsePost.ID, id.trim());
		crit.addAscendingOrder("time");
		Scroller<ResponsePost> results = ResponsePostPeer.doSelect(crit);
		Criteria c = new Criteria();
		c.add(Article.ID, id.trim());
		Scroller<Article> articles = ArticlePeer.doSelect(c);
		Article article = null;
		if (articles.hasNext())
		    article = articles.next();

		request.setAttribute("listing", results);
		request.setAttribute("title", "留言查看");
		request.setAttribute("article", article);
		request.setAttribute("id", id);

		article.setClickcount(article.getClickcount() + 1);
		article.save();
		ActionForward af = mapping.findForward("success");
		return af;
	    }
	    catch (Exception ignore)
	    {
		ignore.printStackTrace();
	    }
	}
	return mapping.getInputForward();
    }
}