/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import resource.WebSetting;

import cn.askrosa.struts.form.FtpSiteUpdateForm;

import database.FtpSitesManager;
import database.FtpSiteInfo;

/**
 * MyEclipse Struts Creation date: 03-10-2008 XDoclet definition:
 * 
 * @struts.action path="/updateFtpSite" name="updateFtpSiteForm"
 *                input="/updateFtpSite.jsp" scope="request" validate="true"
 */
public class FtpSiteUpdateDoAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	FtpSiteUpdateForm updateFtpSiteForm = (FtpSiteUpdateForm) form;
	FtpSiteInfo ftpSite = updateFtpSiteForm.getFtpSiteInfo();
	if (updateFtpSiteForm.getType().equals(
		WebSetting.getProperty("ftpsearch.jsp.updateftpsite.type.update")))
	{
	    String ret = FtpSitesManager.updateFtpSiteWithoutCheck(ftpSite);
	    if (ret != null)
	    {
		ActionMessages errors = new ActionMessages();
		errors.add("ftpSiteInfo.verify", new ActionMessage(ret, false));
		saveErrors(request, errors);
		return mapping.getInputForward();
	    }
	}
	else if (updateFtpSiteForm.getType().equals(
		WebSetting.getProperty("ftpsearch.jsp.updateftpsite.type.delete")))
	{
	    String ret = FtpSitesManager.deleteFtpSite(ftpSite);
	    if (ret != null)
	    {
		ActionMessages errors = new ActionMessages();
		errors.add("ftpSiteInfo.verify", new ActionMessage(ret, false));
		saveErrors(request, errors);
		return mapping.getInputForward();
	    }
	}
	else if (updateFtpSiteForm.getType().equals(
		WebSetting.getProperty("ftpsearch.jsp.updateftpsite.type.immediateindex")))
	{
	    ftpSite.setTotalFileCount(0);
	    try
	    {
		ftpSite.save();
	    }
	    catch (Exception e)
	    {
		ActionMessages errors = new ActionMessages();
		errors.add("ftpSiteInfo.server", new ActionMessage("更新失败", false));
		saveErrors(request, errors);
		return mapping.getInputForward();
	    }
	}
	request.setAttribute("infor", "更新操作成功");
	request.setAttribute("forward", "查看ftp列表");
	request.setAttribute("forwarddo", "ftpSiteList.do");
	return mapping.findForward("success");
    }

}