/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.askrosa.struts.form.SearchForm;

/**
 * MyEclipse Struts Creation date: 05-28-2008 XDoclet definition:
 * 
 * @struts.action path="/singleSiteSearch" name="searchtrueForm"
 * @struts.action-forward name="success" path="/advancedSearch.jsp"
 */
public class SingleSiteSearchAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	SearchForm searchtrueForm = (SearchForm) form;
	String server = request.getParameter("server");
	String keyword = request.getParameter("keyword");
	if (keyword != null)
	{
	    searchtrueForm.setKeyword(keyword);
	    searchtrueForm.setServer(server);
	    searchtrueForm.setField("path");
	    return mapping.findForward("success");
	}
	if (server != null)
	{
	    searchtrueForm.setServer(server);
	    searchtrueForm.setKeyword("");
	}
	return mapping.findForward("success");
    }
}