/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import java.io.File;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import crawlerutils.RosaCrawlerConstants;

import resource.CrawlerSetting;
import database.QueryStatisticsResult;
import database.QueryStatisticsResultPeer;
import database.Scroller;
import draw.DrawStatistics;

/**
 * MyEclipse Struts Creation date: 09-04-2008 XDoclet definition:
 * 
 * @struts.action
 * @struts.action-forward name="success" path="/statistics.jsp"
 */
public class StatisticsShowAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	// 绘图
	File file = new File(CrawlerSetting.getBasePath() + "statistics/hist.png");
	long diff = file.exists()? System.currentTimeMillis()-file.lastModified():Long.MAX_VALUE;
	if (!file.exists() || diff >= RosaCrawlerConstants.ONE_HOUR_IN_MILLISECOND)
	{
	    DrawStatistics d = new DrawStatistics();
	    d.drawGraph(file.getPath());
	}
	// 计算年度热门搜索
	Scroller<QueryStatisticsResult> statisticsResult = QueryStatisticsResultPeer
		.yearlyStatistics(10);
	request.setAttribute("statisticsResult", statisticsResult);
	request.setAttribute("title", "统计信息列表");
	return mapping.findForward("success");
    }
}