/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import database.QueryStatisticsResult;
import database.QueryStatisticsResultPeer;
import database.ResourceRequestPeer;
import database.Scroller;
import database.FtpSiteInfo;
import database.FtpSitesManager;
/**
 * MyEclipse Struts Creation date: 06-01-2008 XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/index.jsp"
 */
public class WelcomemainAction extends Action
{
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */

    public ActionForward execute(ActionMapping mapping, ActionForm form,
	    HttpServletRequest request, HttpServletResponse response)
    {
	try
	{
	    final int pageSize = 5;
	    int page = 1;
	    int from = (page - 1) * 30;
	    
	    request.setAttribute("listing", ResourceRequestPeer.listPagedResourceRequest(null,from,pageSize,null,null,"time",(short)0));	    
	    // 计算热门搜索
	   // Scroller<QueryStatisticsResult> statisticsResult = QueryStatisticsResultPeer
	//	    .weeklyStatistics(10);
	    Scroller<QueryStatisticsResult> statisticsResult = QueryStatisticsResultPeer.statisticsDaysAgo(1,10);
	    // 计算热门站点
	    Scroller<FtpSiteInfo> hotFtpSite=FtpSitesManager.hotFtpSites(6);
	    request.setAttribute("statisticsResult", statisticsResult);
	    request.setAttribute("hotFtpSite", hotFtpSite);
	    return mapping.findForward("success");
	}
	catch (Exception e)
	{
	    e.printStackTrace();
	}
	return mapping.getInputForward();
    }
}