/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2009
 * 
 * XDoclet definition:
 * @struts.form name="articleListForm"
 */
public class ArticleListForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/**
     * 
     */
    private static final long serialVersionUID = -55969730676779183L;

	/** author property */
	private String author;

	/** dateForm property */
	private String dateFrom="";

	/** dateTo property */
	private String dateTo="";

	/** keyword property */
	private String keyword;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the author.
	 * @return String
	 */
	public String getAuthor() {
		return author;
	}

	/** 
	 * Set the author.
	 * @param author The author to set
	 */
	public void setAuthor(String author) {
		this.author = author;
	}


	/** 
	 * Returns the dateTo.
	 * @return String
	 */
	public String getDateTo() {
		return dateTo;
	}

	/** 
	 * Set the dateTo.
	 * @param dateTo The dateTo to set
	 */
	public void setDateTo(String dateTo) {
		this.dateTo = dateTo;
	}

	/** 
	 * Returns the keyword.
	 * @return String
	 */
	public String getKeyword() {
		return keyword;
	}

	/** 
	 * Set the keyword.
	 * @param keyword The keyword to set
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getDateFrom()
	{
	    return dateFrom;
	}

	public void setDateFrom(String dateFrom)
	{
	    this.dateFrom = dateFrom;
	}
}