/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.form;

import org.apache.struts.validator.ValidatorForm;

import database.ResponsePost;

/**
 * MyEclipse Struts Creation date: 09-23-2008 XDoclet definition:
 * 
 * @struts.form name="updateResponsePostForm"
 */
public class ArticleResponsePostUpdateForm extends ValidatorForm
{
    /*
     * Generated fields
     */

    /**
	 * 
	 */
    private static final long serialVersionUID = 134894350741666705L;

    /** responsePost property */
    private ResponsePost responsePost;
    private String type;
    /*
     * Generated Methods
     */

    // /**
    // * Method validate
    // * @param mapping
    // * @param request
    // * @return ActionErrors
    // */
    // public ActionErrors validate(ActionMapping mapping,
    // HttpServletRequest request) {
    // // TODO Auto-generated method stub
    // return null;
    // }
    //
    // /**
    // * Method reset
    // * @param mapping
    // * @param request
    // */
    // public void reset(ActionMapping mapping, HttpServletRequest request) {
    // // TODO Auto-generated method stub
    // }
    /**
     * Returns the responsePost.
     * 
     * @return ResponsePost
     */
    public ResponsePost getResponsePost()
    {
	return responsePost;
    }

    /**
     * Set the responsePost.
     * 
     * @param responsePost
     *            The responsePost to set
     */
    public void setResponsePost(ResponsePost responsePost)
    {
	this.responsePost = responsePost;
    }

    public String getType()
    {
        return type;
    }

    public void setType(String type)
    {
        this.type = type;
    }
}