/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.form;

import org.apache.struts.validator.ValidatorForm;

import database.ResponsePost;

/**
 * MyEclipse Struts Creation date: 09-23-2008 XDoclet definition:
 * 
 * @struts.form name="submitResponsePostForm"
 */
public class ArticleResponsePostForm extends ValidatorForm
{
    /*
     * Generated fields
     */

    /**
	 * 
	 */
    private static final long serialVersionUID = 4053754561545596471L;

    /** article property */
    private ResponsePost responsePost = new ResponsePost();
    private String verifyConfirm;
    private String id;
    /*
     * Generated Methods
     */

    // /**
    // * Method validate
    // * @param mapping
    // * @param request
    // * @return ActionErrors
    // */
    // public ActionErrors validate(ActionMapping mapping,
    // HttpServletRequest request) {
    // // TODO Auto-generated method stub
    // return null;
    // }
    //
    // /**
    // * Method reset
    // * @param mapping
    // * @param request
    // */
    // public void reset(ActionMapping mapping, HttpServletRequest request) {
    // // TODO Auto-generated method stub
    // }
    public String getVerifyConfirm()
    {
	return verifyConfirm;
    }

    public void setVerifyConfirm(String verifyConfirm)
    {
	this.verifyConfirm = verifyConfirm;
    }

    public ResponsePost getResponsePost()
    {
	return responsePost;
    }

    public void setResponsePost(ResponsePost responsePost)
    {
	this.responsePost = responsePost;
    }

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }
}