/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.form;

import org.apache.struts.validator.ValidatorForm;

/**
 * MyEclipse Struts Creation date: 03-09-2009 XDoclet definition:
 * 
 * @struts.form name="articleListForm"
 */
public class FtpSiteSnapshotForm extends ValidatorForm
{
    /**
     * 
     */
    private static final long serialVersionUID = -3126475586558536969L;
    private String preServer="";
    private String ftpInfo="";
    private String ftpAddress="";
    private String preUsername="anonymous";
    public String getFtpInfo()
    {
        return ftpInfo;
    }

    public void setFtpInfo(String ftpInfo)
    {
        this.ftpInfo = ftpInfo;
    }

    public String getPreServer()
    {
        return preServer;
    }

    public void setPreServer(String preServer)
    {
        this.preServer = preServer;
    }

    public String getFtpAddress()
    {
        return ftpAddress;
    }

    public void setFtpAddress(String ftpAddress)
    {
        this.ftpAddress = ftpAddress;
    }

    public String getPreUsername()
    {
        return preUsername;
    }

    public void setPreUsername(String preUsername)
    {
        this.preUsername = preUsername;
    }
}