/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2009
 * 
 * XDoclet definition:
 * @struts.form name="articleListForm"
 */
public class ResourceRequestListForm extends ValidatorForm {
	/**
     * 
     */
    private static final long serialVersionUID = -3023316172498515877L;

	/*
	 * Generated fields
	 */

	/**
     * 
     
	/** dateForm property */
	private String dateFrom;

	/** dateTo property */
	private String dateTo;

	/** keyword property */
	private String keyword;
	      	
	private short state=-1;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the dateTo.
	 * @return String
	 */
	public String getDateTo() {
		return dateTo;
	}

	/** 
	 * Set the dateTo.
	 * @param dateTo The dateTo to set
	 */
	public void setDateTo(String dateTo) {
		this.dateTo = dateTo;
	}

	/** 
	 * Returns the keyword.
	 * @return String
	 */
	public String getKeyword() {
		return keyword;
	}

	/** 
	 * Set the keyword.
	 * @param keyword The keyword to set
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public short getState()
	{
	    return state;
	}

	public void setState(short state)
	{
	    this.state = state;
	}

	public String getDateFrom()
	{
	    return dateFrom;
	}

	public void setDateFrom(String dateFrom)
	{
	    this.dateFrom = dateFrom;
	}

}