/*
 * Generated by MyEclipse Struts Template path: templates/java/JavaClass.vtl
 */
package cn.askrosa.struts.form;

import java.util.Enumeration;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/**
 * MyEclipse Struts Creation date: 03-02-2008 XDoclet definition:
 * 
 * @struts.form name="searchtrueForm"
 */
public class SearchForm extends ValidatorForm
{
    /**
     * 
     */
    private static final long serialVersionUID = 7489006234077477085L;

    /*
     * Generated Methods
     */

    /** keywordExclude property */
    private String keywordExclude;

    /** categories property */
    private String[] categories = null;

    /** access property */
    private String access;

    /** sever property */
    private String server;

    private String keyword;

    private String dateFrom;

    private String dateTo;

    private String field = "name";

    private String sort = "default";

    private String pageIndex;

    private short[] locations = null;

    /**
     * @return the field
     */
    public String getField()
    {
	return field;
    }

    /**
     * @param field
     *                the field to set
     */
    public void setField(String field)
    {
	this.field = field;
    }

    public String getKeyword()
    {
	return this.keyword;
    }

    public void setKeyword(String keyword)
    {
	this.keyword = keyword.trim();
    }

    /**
     * Returns the keywordExclude.
     * 
     * @return String
     */
    public String getKeywordExclude()
    {
	return keywordExclude;
    }

    /**
     * Set the keywordExclude.
     * 
     * @param keywordExclude
     *                The keywordExclude to set
     */
    public void setKeywordExclude(String keywordExclude)
    {
	this.keywordExclude = keywordExclude;
    }

    /**
     * Returns the categories.
     * 
     * @return String
     */
    public String[] getCategories()
    {
	return categories;
    }

    /**
     * Set the categories.
     * 
     * @param categories
     *                The categories to set
     */
    public void setCategories(String[] categories)
    {
	this.categories = categories;
    }

    /**
     * Returns the access.
     * 
     * @return String
     */
    public String getAccess()
    {
	return access;
    }

    /**
     * Set the access.
     * 
     * @param access
     *                The access to set
     */
    public void setAccess(String access)
    {
	this.access = access;
    }

    /**
     * Returns the sever.
     * 
     * @return String
     */
    public String getServer()
    {
	return server;
    }

    /**
     * Set the sever.
     * 
     * @param sever
     *                The sever to set
     */
    public void setServer(String server)
    {
	this.server = server;
    }

    /**
     * Method reset
     * 
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request)
    {
	super.reset(mapping, request);
	Enumeration<?> en = request.getParameterNames();
	boolean hasCategories = false;
	boolean hasLocations = false;
	boolean hasKeyword = false;
	while (en.hasMoreElements())
	{
	    String enele = en.nextElement().toString();
	    if (enele.equals("keyword"))
		hasKeyword = true;
	    if (enele.equals("categories"))
		hasCategories = true;
	    if (enele.equals("locations"))
		hasCategories = true;
	}
	if (hasKeyword == true && hasCategories == false)
	    this.setCategories(null);
	if (hasKeyword == true && hasLocations == false)
	    this.setLocations(null);
    }

    public String getDateFrom()
    {
	return dateFrom;
    }

    public void setDateFrom(String dateFrom)
    {
	this.dateFrom = dateFrom;
    }

    public String getDateTo()
    {
	return dateTo;
    }

    public void setDateTo(String dateTo)
    {
	this.dateTo = dateTo;
    }

    public String getPageIndex()
    {
	return pageIndex;
    }

    public void setPageIndex(String pageIndex)
    {
	this.pageIndex = pageIndex;
    }

    public String getSort()
    {
	return sort;
    }

    public void setSort(String sort)
    {
	this.sort = sort;
    }

    public short[] getLocations()
    {
        return locations;
    }

    public void setLocations(short[] locations)
    {
        this.locations = locations;
    }
}